spring:
  application:
    name: hoardr

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mydb
      username: admin
      password: root
      authentication-database: admin

#      uri: mongodb://localhost:27017/mydb

  graphql:
    graphiql:
      enabled: true
