spring:
  application:
    name: hoardr

#    data:
#      mongodb:
#        uri: mongodb://root:root@localhost:27017/cardcollectiondb?authSource=admin

  data:
    mongodb:
      port: 27017
      host: mongodb

  graphql:
    graphiql:
      enabled: true

server:
  error:
    include-messages: always